# Конфигурация плагина FreezeEffectPlugin
# Добавьте блоки, которые должны вызывать заморозку, по одной строке на каждый блок.
freezing-blocks:
  - ICE
  - PACKED_ICE
  - BLUE_ICE
  - SNOW_BLOCK

# Время действия заморозки в тиках (20 тиков = 1 секунда)
freeze-duration: 140

# Время (в миллисекундах), которое игрок должен простоять на блоке, чтобы заморозка активировалась
time-to-freeze: 1000
